package de.bitgilde.TIMAAT.storage.entity.transcription.api;

/**
 * Type of the {@link de.bitgilde.TIMAAT.model.FIPOP.Transcription}.
 * Transcriptions can be generated by using the speech-to-text-service or imported from a file
 *
 * @author Nico Kotlenga (nico@nko-dev.studio) 
 * @since 12.05.26
 */
public enum TranscriptionType {
  GENERATED(1),
  IMPORTED(2);

  private final int databaseId;

  TranscriptionType(int databaseId) {
    this.databaseId = databaseId;
  }

  public int getDatabaseId() {
    return databaseId;
  }
}
