package de.bitgilde.TIMAAT.storage.entity.transcription.api;

/**
 * Type of the {@link de.bitgilde.TIMAAT.model.FIPOP.Transcription}.
 * Transcriptions can be generated by using the speech-to-text-service or imported from a file
 *
 * @author Nico Kotlenga (nico@nko-dev.studio) 
 * @since 12.05.26
 */
public enum TranscriptionType {
  GENERATED(1),
  IMPORTED(2);

  private final int databaseId;

  TranscriptionType(int databaseId) {
    this.databaseId = databaseId;
  }

  public int getDatabaseId() {
    return databaseId;
  }

  /**
   * Looks up the enum constant whose {@link #getDatabaseId()} matches the given id.
   *
   * @param databaseId the {@code transcription_type.id} value persisted in the DB
   * @return the matching enum constant
   * @throws IllegalArgumentException if no constant has the given database id
   */
  public static TranscriptionType fromDatabaseId(int databaseId) {
    for (TranscriptionType type : values()) {
      if (type.databaseId == databaseId) {
        return type;
      }
    }
    throw new IllegalArgumentException("No TranscriptionType with database id " + databaseId);
  }
}
