# Copyright 2019 bitGilde IT Solutions UG (haftungsbeschr\u00e4nkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file contains the system-specific properties for your TIMAAT installation.
# Path to directory where binaries are stored.
storage.location=/opt/timaat/files/ # Linux
# storage.location = c:\\fipop\\files\\ # Windows
storage.temp.location=/tmp/timaat
#name="jakarta.persistence.jdbc.driver" value="com.mysql.cj.jdbc.Driver"
database.driver=com.mysql.cj.jdbc.Driver
# name="jakarta.persistence.jdbc.url"
database.url=jdbc:mysql://localhost:3306/FIPOP?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&maxIdleTime=180&useMysqlMetadata=true
#name="jakarta.persistence.jdbc.user" value="root"
database.user=root
#name="jakarta.persistence.jdbc.password" value="geheim123"
database.password=geheim123
# Path to FFMPEG dir
app.ffmpeg.location=/usr/bin/ # Linux
# app.ffmpeg.location = c:\\ffmpeg\\bin\\ # Windows
# Path to ImageMagick dir
app.imagemagick.location=/usr/bin/
# Maximum amount of threads which will be spanned to run tasks
app.task.coreParallelCount=2
# Count of thread which are always ready for task execution
app.task.maxParallelCount=4
# Maximum queue size of async tasks
app.task.queueSize=1000
# Switch to activate or deactivate speech to text capabilities
stt.enabled=false
# Host on which the speech-to-text-service is currently running
stt.host=127.0.0.1
# Host port on which the speech-to-text-service currently binded
stt.port=8080
# Path to trusted certificate of the connection to the speech-to-text-service
stt.trustedServerCertificatePath=path/to/trusted/server/certificate/path
# Type of transfer to exchange audio and result files. Can be STREAMING or SHARED_STORAGE
stt.transfer.type=STREAMING
# Defines the shared storage location used for audio files on transfer type SHARED_STORAGE
stt.transfer.sharedAudioStoragePath=path/to/shared/audio/storage
# Defines the shared storage location used for results on transfer type SHARED_STORAGE
stt.transfer.sharedResultStoragePath=path/to/shared/result/storage
# Defines whether a certificate authentication is performed when connection to speech-to-text-service
stt.auth.enabled=false
# Path of the certificate used when certificate authentication is enabled
stt.auth.certificatePath=path/to/auth/certificate
# Path of the private key used when certificate authentication is enabled
stt.auth.privateKeyPath=path/to/private/key
# Optional private key pasword
stt.auth.privateKeyPassword=password